### ISSUE TITLE
Broken requirements.txt because of changes in opencv-contrib library

### ISSUE THREAD

**Issue by Purefekt** [saifkhichi96/signature-extraction#1]
**Describe the bug**
Because of patented algorithms like surf and sift being removed from opencv-contrib, installing via the given method in the readme is not working.

**To Reproduce**
Try installing and running the program.

**Expected behavior**
Opencv-contrib library wont install

**How to fix**
I installed the following packages in a conda environment one by one and then used a special flag to install opencv-contrib and it worked
## Installation - WORKING USING CONDA
Create conda environment with the name 'signature_extraction' and activate virtual env
```
conda create --name signature_extraction

conda activate signature_extraction
```
Install packages one by one (requirements.txt not working properly because of different channels)
```
conda install -c anaconda joblib

conda install -c anaconda numpy

conda install -c anaconda scikit-learn

conda install -c anaconda scipy

conda install -c conda-forge opencv

conda install -c conda-forge threadpoolctl

conda install -c conda-forge tqdm
```
opencv-contrib package will have to be built from source with NONFREE flag set. If this package installed directly then we wont be able to use a crucial function in the code. This might take some time.
```
CMAKE_ARGS="-DOPENCV_ENABLE_NONFREE=ON" pip install --no-binary=opencv-contrib-python opencv-contrib-python

```
Once all packages are installed to the virtual env, cd to the project directory and run the GUI app with
```
python3 src/extract_gui.py
```

**Comment by saifkhichi96** [comment]
You need an older version of `opencv-contrib-python` and `opencv-python`. Something 3.+ but before 3.4.2.17. Let me know if it works. Try using `pip` inside the anaconda environment, it should install the package in the environment. `pip install opencv-contrib-python=3.4.2.17` should work. You can find available versions at https://pypi.org/project/opencv-contrib-python/#history

**Comment by saifkhichi96** [comment]
Closed due to inactivity.
